Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace SchedulerMVVMScenarioWpf

    Partial Public Class CarsXtraSchedulingEntities
        Inherits DbContext

        Public Sub New()
            MyBase.New("name=CarsXtraSchedulingEntities")
        End Sub

        Protected Overrides Sub OnModelCreating(ByVal modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub

        Public Property Cars() As DbSet(Of Car)
        Public Property CarSchedulings() As DbSet(Of CarScheduling)
    End Class
End Namespace
